// Dummy product data
final List<Map<String, dynamic>> allProducts = [
  {
    'id': 'p1',
    'name': 'iPhone 12 Pro',
    'category': 'Smartphones',
    'condition': 'Good',
    'description':
        'Slightly used iPhone 12 Pro with minor scratches on the back. Battery health at 89%.',
    'price': 450.00,
    'originalPrice': 999.00,
    'distance': 2.5,
    'postedDate': DateTime.now().subtract(const Duration(days: 2)),
    'seller': {
      'name': 'TechRecycle Inc.',
      'rating': 4.8,
      'isVerified': true,
      'type': 'organization',
    },
    'images': [
      'https://images.unsplash.com/photo-1603891128711-11b4b03bb138?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aXBob25lJTIwMTIlMjBwcm98ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
    ],
    'tags': ['trending', 'value'],
    'isFeatured': true,
    'views': 342,
    'bids': 5,
  },
  {
    'id': 'p2',
    'name': 'MacBook Pro 2019',
    'category': 'Laptops',
    'condition': 'Excellent',
    'description':
        'MacBook Pro 2019 model with 16GB RAM and 512GB SSD. Barely used and in excellent condition.',
    'price': 850.00,
    'originalPrice': 1799.00,
    'distance': 5.1,
    'postedDate': DateTime.now().subtract(const Duration(days: 5)),
    'seller': {
      'name': 'Green Tech Solutions',
      'rating': 4.9,
      'isVerified': true,
      'type': 'organization',
    },
    'images': [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bWFjYm9vayUyMHByb3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'tags': ['premium', 'trending'],
    'isFeatured': true,
    'views': 521,
    'bids': 12,
  },
  {
    'id': 'p3',
    'name': 'Samsung Galaxy S21',
    'category': 'Smartphones',
    'condition': 'Fair',
    'description':
        'Samsung Galaxy S21 with cracked screen but fully functional. Battery health at 92%.',
    'price': 220.00,
    'originalPrice': 799.00,
    'distance': 1.8,
    'postedDate': DateTime.now().subtract(const Duration(days: 1)),
    'seller': {
      'name': 'Alex Johnson',
      'rating': 4.2,
      'isVerified': false,
      'type': 'individual',
    },
    'images': [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c2Ftc3VuZyUyMGdhbGF4eSUyMHMyMXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'tags': ['value', 'forYou'],
    'isFeatured': false,
    'views': 187,
    'bids': 3,
  },
  {
    'id': 'p4',
    'name': 'Dell XPS 15',
    'category': 'Laptops',
    'condition': 'Good',
    'description':
        'Dell XPS 15 with 32GB RAM and 1TB SSD. Some wear on the keyboard but works perfectly.',
    'price': 780.00,
    'originalPrice': 1699.00,
    'distance': 8.3,
    'postedDate': DateTime.now().subtract(const Duration(days: 7)),
    'seller': {
      'name': 'EcoTech Recyclers',
      'rating': 4.7,
      'isVerified': true,
      'type': 'organization',
    },
    'images': [
      'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZGVsbCUyMHhwc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'tags': ['premium', 'value'],
    'isFeatured': false,
    'views': 276,
    'bids': 8,
  },
  {
    'id': 'p5',
    'name': 'iPad Pro 12.9"',
    'category': 'Tablets',
    'condition': 'Excellent',
    'description':
        'iPad Pro 12.9" 2021 model with Apple Pencil included. Like new condition with screen protector.',
    'price': 650.00,
    'originalPrice': 1099.00,
    'distance': 3.7,
    'postedDate': DateTime.now().subtract(const Duration(days: 3)),
    'seller': {
      'name': 'TechReclaim Center',
      'rating': 4.6,
      'isVerified': true,
      'type': 'organization',
    },
    'images': [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8aXBhZCUyMHByb3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'tags': ['premium', 'trending', 'forYou'],
    'isFeatured': true,
    'views': 412,
    'bids': 9,
  },
  {
    'id': 'p6',
    'name': 'Sony PlayStation 5',
    'category': 'Gaming',
    'condition': 'Good',
    'description':
        'PS5 with two controllers and 3 games. Minor scratches on the console but works perfectly.',
    'price': 420.00,
    'originalPrice': 599.00,
    'distance': 6.2,
    'postedDate': DateTime.now().subtract(const Duration(days: 10)),
    'seller': {
      'name': 'GameCycle Hub',
      'rating': 4.5,
      'isVerified': true,
      'type': 'organization',
    },
    'images': [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGxheXN0YXRpb24lMjA1fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'tags': ['trending', 'forYou'],
    'isFeatured': false,
    'views': 589,
    'bids': 15,
  },
  {
    'id': 'p7',
    'name': 'Apple Watch Series 6',
    'category': 'Wearables',
    'condition': 'Fair',
    'description':
        'Apple Watch Series 6 with some scratches on the screen. Battery lasts about a day.',
    'price': 180.00,
    'originalPrice': 399.00,
    'distance': 4.5,
    'postedDate': DateTime.now().subtract(const Duration(days: 15)),
    'seller': {
      'name': 'Sarah Williams',
      'rating': 4.3,
      'isVerified': false,
      'type': 'individual',
    },
    'images': [
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YXBwbGUlMjB3YXRjaHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'tags': ['value', 'forYou'],
    'isFeatured': false,
    'views': 203,
    'bids': 4,
  },
  {
    'id': 'p8',
    'name': 'Bose QuietComfort 35 II',
    'category': 'Audio',
    'condition': 'Good',
    'description':
        'Bose QuietComfort 35 II noise-cancelling headphones. Comes with original case and cables.',
    'price': 150.00,
    'originalPrice': 349.00,
    'distance': 7.8,
    'postedDate': DateTime.now().subtract(const Duration(days: 8)),
    'seller': {
      'name': 'AudioPhile Recyclers',
      'rating': 4.4,
      'isVerified': true,
      'type': 'organization',
    },
    'images': [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8Ym9zZSUyMGhlYWRwaG9uZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
    ],
    'tags': ['value', 'trending'],
    'isFeatured': false,
    'views': 245,
    'bids': 6,
  },
  {
    'id': 'p9',
    'name': 'Canon EOS R5',
    'category': 'Cameras',
    'condition': 'Excellent',
    'description':
        'Canon EOS R5 mirrorless camera with 24-105mm lens. Low shutter count and like new condition.',
    'price': 2800.00,
    'originalPrice': 3899.00,
    'distance': 12.3,
    'postedDate': DateTime.now().subtract(const Duration(days: 20)),
    'seller': {
      'name': 'Pro Camera Exchange',
      'rating': 4.9,
      'isVerified': true,
      'type': 'organization',
    },
    'images': [
      'https://images.unsplash.com/photo-1585155770447-2f66e2a397b5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2Fub24lMjBjYW1lcmF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
    ],
    'tags': ['premium'],
    'isFeatured': true,
    'views': 178,
    'bids': 3,
  },
  {
    'id': 'p10',
    'name': 'Nintendo Switch',
    'category': 'Gaming',
    'condition': 'Good',
    'description':
        'Nintendo Switch with dock, controllers, and 5 games. Some wear on the joy-cons but works great.',
    'price': 220.00,
    'originalPrice': 299.00,
    'distance': 5.6,
    'postedDate': DateTime.now().subtract(const Duration(days: 12)),
    'seller': {
      'name': 'Michael Chen',
      'rating': 4.1,
      'isVerified': false,
      'type': 'individual',
    },
    'images': [
      'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bmludGVuZG8lMjBzd2l0Y2h8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
    ],
    'tags': ['value', 'forYou'],
    'isFeatured': false,
    'views': 312,
    'bids': 7,
  },
];

// Featured products
final List<Map<String, dynamic>> featuredProducts = [
  {
    'id': 'f1',
    'name': 'iPhone 12 Pro Max',
    'category': 'Phones',
    'condition': 'Good',
    'originalPrice': 899.99,
    'discountedPrice': 649.99,
    'distance': 1.2,
    'seller': {
      'name': 'TechRecycle Inc.',
      'isVerified': true,
      'rating': 4.8,
      'image': 'https://randomuser.me/api/portraits/men/32.jpg',
    },
    'views': 342,
    'bids': 8,
    'description':
        'Slightly used iPhone 12 Pro Max with 256GB storage. Minor scratches on the back, but screen is in perfect condition. Comes with original charger and box.',
    'images': [
      'https://images.unsplash.com/photo-1603891128711-11b4b03bb138?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aXBob25lJTIwMTIlMjBwcm98ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      'https://images.unsplash.com/photo-1611472173362-3f53dbd65d80?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8aXBob25lJTIwMTIlMjBwcm98ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
    ],
    'specs': {
      'Storage': '256GB',
      'Color': 'Pacific Blue',
      'Battery Health': '89%',
      'Included': 'Original box, charger, cable',
    },
    'auction': {
      'endDate': '2023-05-15',
      'startingPrice': 499.99,
      'currentBid': 599.99,
      'bidders': [
        {'name': 'Alex M.', 'bid': 599.99, 'date': '2023-05-10'},
        {'name': 'Sarah K.', 'bid': 580.00, 'date': '2023-05-09'},
        {'name': 'Mike T.', 'bid': 550.00, 'date': '2023-05-08'},
        {'name': 'Jessica L.', 'bid': 520.00, 'date': '2023-05-07'},
        {'name': 'David R.', 'bid': 499.99, 'date': '2023-05-06'},
      ],
    },
  },
  {
    'id': 'f2',
    'name': 'MacBook Pro 2019',
    'category': 'Laptops',
    'condition': 'Like New',
    'originalPrice': 1299.99,
    'discountedPrice': 899.99,
    'distance': 3.5,
    'seller': {
      'name': 'GreenTech Solutions',
      'isVerified': true,
      'rating': 4.6,
      'image': 'https://randomuser.me/api/portraits/women/44.jpg',
    },
    'views': 521,
    'bids': 12,
    'description':
        '2019 MacBook Pro with 16-inch display, 16GB RAM, and 512GB SSD. Barely used and in excellent condition. Includes original packaging and accessories.',
    'images': [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bWFjYm9vayUyMHByb3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8bWFjYm9vayUyMHByb3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'specs': {
      'Processor': 'Intel Core i5',
      'RAM': '8GB',
      'Storage': '256GB SSD',
      'Display': '13-inch Retina',
      'Battery Cycles': '310',
    },
    'auction': {
      'endDate': '2023-05-18',
      'startingPrice': 699.99,
      'currentBid': 799.99,
      'bidders': [
        {'name': 'Thomas W.', 'bid': 799.99, 'date': '2023-05-12'},
        {'name': 'Emma S.', 'bid': 750.00, 'date': '2023-05-11'},
        {'name': 'Robert J.', 'bid': 720.00, 'date': '2023-05-10'},
        {'name': 'Lisa M.', 'bid': 699.99, 'date': '2023-05-09'},
      ],
    },
  },
  {
    'id': 'f3',
    'name': 'Samsung 4K QLED TV',
    'category': 'Monitors',
    'condition': 'Good',
    'originalPrice': 1499.99,
    'discountedPrice': 899.99,
    'distance': 5.7,
    'seller': {
      'name': 'ElectroRecycle',
      'rating': 4.3,
      'isVerified': false,
      'image': 'https://randomuser.me/api/portraits/men/22.jpg',
    },
    'views': 287,
    'bids': 5,
    'description':
        '55-inch Samsung QLED 4K Smart TV. Some minor scratches on the stand but screen is perfect. Remote control included.',
    'images': [
      'https://images.unsplash.com/photo-1589739900243-4b52cd9dd8df?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8dGFibGV0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
      'https://images.unsplash.com/photo-1623126908029-58cb08a2b272?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8dGFibGV0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'specs': {
      'Display': '11-inch LTPS TFT',
      'Storage': '128GB',
      'RAM': '6GB',
      'Battery': '8,000 mAh',
      'Included': 'S Pen, protective case, charger',
    },
    'auction': {
      'endDate': '2023-05-20',
      'startingPrice': 399.99,
      'currentBid': 449.99,
      'bidders': [
        {'name': 'Jennifer P.', 'bid': 449.99, 'date': '2023-05-13'},
        {'name': 'Brian K.', 'bid': 425.00, 'date': '2023-05-12'},
        {'name': 'Amanda S.', 'bid': 399.99, 'date': '2023-05-11'},
      ],
    },
  },
];

// For You products
final List<Map<String, dynamic>> forYouProducts = [
  {
    'id': 'p1',
    'name': 'Dell XPS 15',
    'category': 'Laptops',
    'condition': 'Good',
    'originalPrice': 1199.99,
    'discountedPrice': 799.99,
    'distance': 2.3,
    'seller': {
      'name': 'Tech Salvage Co.',
      'isVerified': true,
      'rating': 4.7,
      'image': 'https://randomuser.me/api/portraits/men/42.jpg',
    },
    'views': 187,
    'bids': 4,
    'images': [
      'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8ZGVsbCUyMGxhcHRvcHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'description':
        'Dell XPS 15 (2019) with 4K display, Intel Core i7, 16GB RAM, and 512GB SSD. Some wear on the keyboard but otherwise in good condition.',
    'specs': {
      'Processor': 'Intel Core i7-9750H',
      'RAM': '16GB',
      'Storage': '512GB SSD',
      'Display': '15.6-inch 4K UHD',
      'Graphics': 'NVIDIA GTX 1650',
    },
    'auction': {
      'endDate': '2023-05-17',
      'startingPrice': 799.99,
      'currentBid': 899.99,
      'bidders': [
        {'name': 'Chris M.', 'bid': 899.99, 'date': '2023-05-12'},
        {'name': 'Laura B.', 'bid': 850.00, 'date': '2023-05-11'},
        {'name': 'Kevin P.', 'bid': 825.00, 'date': '2023-05-10'},
        {'name': 'Sophia R.', 'bid': 799.99, 'date': '2023-05-09'},
      ],
    },
  },
  {
    'id': 'p2',
    'name': 'iPad Pro 12.9"',
    'category': 'Tablets',
    'condition': 'Like New',
    'originalPrice': 899.99,
    'discountedPrice': 699.99,
    'distance': 1.8,
    'seller': {
      'name': 'Apple Recyclers',
      'isVerified': true,
      'rating': 4.5,
      'image': 'https://randomuser.me/api/portraits/women/22.jpg',
    },
    'views': 231,
    'bids': 7,
    'images': [
      'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8aGVhZHBob25lc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'description':
        'Sony WH-1000XM4 wireless noise-cancelling headphones. Barely used, in excellent condition with all original accessories and packaging.',
    'specs': {
      'Type': 'Over-ear, wireless',
      'Battery Life': 'Up to 30 hours',
      'Connectivity': 'Bluetooth 5.0, 3.5mm',
      'Features': 'Active noise cancellation, touch controls',
      'Included': 'Carrying case, charging cable, audio cable',
    },
    'auction': {
      'endDate': '2023-05-16',
      'startingPrice': 199.99,
      'currentBid': 229.99,
      'bidders': [
        {'name': 'Daniel K.', 'bid': 229.99, 'date': '2023-05-11'},
        {'name': 'Rachel W.', 'bid': 215.00, 'date': '2023-05-10'},
        {'name': 'Jason L.', 'bid': 199.99, 'date': '2023-05-09'},
      ],
    },
  },
  {
    'id': 'p3',
    'name': 'Sony Alpha A7 III',
    'category': 'Cameras',
    'condition': 'Good',
    'originalPrice': 1799.99,
    'discountedPrice': 1299.99,
    'distance': 4.1,
    'seller': {
      'name': 'Camera Exchange',
      'isVerified': false,
      'rating': 4.9,
      'image': 'https://randomuser.me/api/portraits/men/62.jpg',
    },
    'views': 156,
    'bids': 3,
    'images': [
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2Fub24lMjBjYW1lcmF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
    ],
    'description':
        'Canon EOS 80D DSLR camera with 18-135mm lens. Some signs of use but in good working condition. Includes battery, charger, and camera bag.',
    'specs': {
      'Sensor': '24.2MP APS-C CMOS',
      'Processor': 'DIGIC 6',
      'Autofocus': '45-point all cross-type AF',
      'Video': '1080p at 60fps',
      'Shutter Count': 'Approx. 15,000',
    },
    'auction': {
      'endDate': '2023-05-19',
      'startingPrice': 499.99,
      'currentBid': 599.99,
      'bidders': [
        {'name': 'Michael B.', 'bid': 599.99, 'date': '2023-05-13'},
        {'name': 'Emily C.', 'bid': 550.00, 'date': '2023-05-12'},
        {'name': 'Andrew T.', 'bid': 525.00, 'date': '2023-05-11'},
        {'name': 'Nicole S.', 'bid': 499.99, 'date': '2023-05-10'},
      ],
    },
  },
  {
    'id': 'p4',
    'name': 'Samsung Galaxy S21',
    'category': 'Phones',
    'condition': 'Fair',
    'originalPrice': 699.99,
    'discountedPrice': 399.99,
    'distance': 3.2,
    'seller': {
      'name': 'Phone Rescue',
      'isVerified': true,
      'rating': 4.8,
      'image': 'https://randomuser.me/api/portraits/women/32.jpg',
    },
    'views': 203,
    'bids': 9,
    'images': [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8aXBhZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'description':
        'iPad Pro 11-inch (2020) with 256GB storage, Wi-Fi + Cellular. Minor scratches on the back but screen is flawless. Includes Apple Pencil 2nd gen.',
    'specs': {
      'Chip': 'A12Z Bionic',
      'Storage': '256GB',
      'Display': '11-inch Liquid Retina',
      'Connectivity': 'Wi-Fi + Cellular',
      'Included': 'Apple Pencil 2nd gen, charger',
    },
    'auction': {
      'endDate': '2023-05-18',
      'startingPrice': 549.99,
      'currentBid': 599.99,
      'bidders': [
        {'name': 'Jessica T.', 'bid': 599.99, 'date': '2023-05-12'},
        {'name': 'Ryan M.', 'bid': 575.00, 'date': '2023-05-11'},
        {'name': 'Olivia P.', 'bid': 549.99, 'date': '2023-05-10'},
      ],
    },
  },
];

// Value for Money products
final List<Map<String, dynamic>> valueProducts = [
  {
    'id': 'v1',
    'name': 'Logitech MX Master 3',
    'category': 'Accessories',
    'condition': 'Like New',
    'originalPrice': 99.99,
    'discountedPrice': 59.99,
    'distance': 1.5,
    'seller': {
      'name': 'Peripheral Plus',
      'isVerified': true,
      'rating': 4.6,
      'image': 'https://randomuser.me/api/portraits/men/52.jpg',
    },
    'views': 124,
    'bids': 6,
    'images': [
      'https://images.unsplash.com/photo-1583573636246-18cb2246697a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Z2FsYXh5JTIwczIwfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'description':
        'Samsung Galaxy S20 with 128GB storage. Some minor scratches on the screen but fully functional. Includes original charger and box.',
    'specs': {
      'Display': '6.2-inch Dynamic AMOLED',
      'Processor': 'Exynos 990',
      'RAM': '8GB',
      'Storage': '128GB',
      'Battery': '4,000 mAh',
    },
    'auction': {
      'endDate': '2023-05-16',
      'startingPrice': 299.99,
      'currentBid': 349.99,
      'bidders': [
        {'name': 'Mark L.', 'bid': 349.99, 'date': '2023-05-11'},
        {'name': 'Sophia K.', 'bid': 325.00, 'date': '2023-05-10'},
        {'name': 'James R.', 'bid': 299.99, 'date': '2023-05-09'},
      ],
    },
  },
  {
    'id': 'v2',
    'name': 'HP Color LaserJet Pro',
    'category': 'Printers',
    'condition': 'Good',
    'originalPrice': 349.99,
    'discountedPrice': 179.99,
    'distance': 2.7,
    'seller': {
      'name': 'Office Depot Recycling',
      'isVerified': false,
      'rating': 4.4,
      'image': 'https://randomuser.me/api/portraits/women/12.jpg',
    },
    'views': 98,
    'bids': 2,
    'images': [
      'https://images.unsplash.com/photo-1629429407759-01cd3d7cfb38?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bG9naXRlY2glMjBtb3VzZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'description':
        'Logitech MX Master 3 wireless mouse in excellent condition. Barely used, comes with original packaging and USB receiver.',
    'specs': {
      'Connectivity': 'Bluetooth, USB receiver',
      'Battery Life': 'Up to 70 days',
      'Buttons': '7 programmable buttons',
      'Compatibility': 'Windows, macOS, Linux',
      'Features': 'MagSpeed scroll wheel, app-specific profiles',
    },
    'auction': {
      'endDate': '2023-05-15',
      'startingPrice': 49.99,
      'currentBid': 59.99,
      'bidders': [
        {'name': 'David C.', 'bid': 59.99, 'date': '2023-05-10'},
        {'name': 'Anna M.', 'bid': 54.99, 'date': '2023-05-09'},
        {'name': 'Paul S.', 'bid': 49.99, 'date': '2023-05-08'},
      ],
    },
  },
  {
    'id': 'v3',
    'name': 'Bose QuietComfort 35 II',
    'category': 'Accessories',
    'condition': 'Good',
    'originalPrice': 299.99,
    'discountedPrice': 149.99,
    'distance': 3.9,
    'seller': {
      'name': 'Audio Recyclers',
      'isVerified': true,
      'rating': 4.5,
      'image': 'https://randomuser.me/api/portraits/men/72.jpg',
    },
    'views': 176,
    'bids': 8,
    'images': [
      'https://images.unsplash.com/photo-1527219525722-f9767a7f2884?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8Z2FtaW5nJTIwbW9uaXRvcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'description':
        '27-inch Acer Predator gaming monitor with 1440p resolution and 144Hz refresh rate. Some scratches on the stand and a small dead pixel in the corner.',
    'specs': {
      'Display': '27-inch IPS',
      'Resolution': '2560 x 1440 (WQHD)',
      'Refresh Rate': '144Hz',
      'Response Time': '4ms',
      'Ports': 'HDMI, DisplayPort, USB 3.0 hub',
    },
    'auction': {
      'endDate': '2023-05-17',
      'startingPrice': 199.99,
      'currentBid': 249.99,
      'bidders': [
        {'name': 'Eric T.', 'bid': 249.99, 'date': '2023-05-12'},
        {'name': 'Michelle L.', 'bid': 225.00, 'date': '2023-05-11'},
        {'name': 'Brandon K.', 'bid': 210.00, 'date': '2023-05-10'},
        {'name': 'Samantha P.', 'bid': 199.99, 'date': '2023-05-09'},
      ],
    },
  },
  // {
  //   'id': 'v4',
  //   'name': 'Acer Predator Monitor',
  //   'category': 'Monitors',
  //   'condition': 'Fair',
  //   'originalPrice': 449.99,
  //   'discountedPrice': 229.99,
  //   'distance': 5.3,
  //   'image': 'https://images.unsplash.com/photo-1527219525722-f9767a7f2884',
  //   'seller': {
  //     'name': 'Gaming Gear Recycled',
  //     'isVerified': false,
  //     'image': 'https://randomuser.me/api/portraits/women/62.jpg',
  //   },
  //   'views': 143,
  //   'bids': 4,
  // },
];

// Trending products
final List<Map<String, dynamic>> trendingProducts = [
  {
    'id': 't1',
    'name': 'Nintendo Switch',
    'category': 'Gaming',
    'condition': 'Good',
    'originalPrice': 299.99,
    'discountedPrice': 219.99,
    'distance': 2.1,
    'seller': {
      'name': 'Game Exchange',
      'isVerified': true,
      'rating': 4.7,
      'image': 'https://randomuser.me/api/portraits/men/22.jpg',
    },
    'views': 312,
    'bids': 15,
    'images': [
      'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bmludGVuZG8lMjBzd2l0Y2h8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
    ],
    'description':
        'Nintendo Switch console (V2) with improved battery life. Includes dock, Joy-Cons, and all original accessories. Some light scratches on the screen.',
    'specs': {
      'Model': 'HAC-001(-01)',
      'Storage': '32GB (expandable)',
      'Battery Life': '4.5-9 hours',
      'Included': 'Dock, Joy-Cons, Joy-Con grip, HDMI cable, AC adapter',
      'Games': 'None included',
    },
    'auction': {
      'endDate': '2023-05-15',
      'startingPrice': 189.99,
      'currentBid': 219.99,
      'bidders': [
        {'name': 'Tyler J.', 'bid': 219.99, 'date': '2023-05-10'},
        {'name': 'Megan R.', 'bid': 205.00, 'date': '2023-05-09'},
        {'name': 'Justin K.', 'bid': 195.00, 'date': '2023-05-08'},
        {'name': 'Amber L.', 'bid': 189.99, 'date': '2023-05-07'},
      ],
    },
  },
  {
    'id': 't2',
    'name': 'DJI Mavic Air 2',
    'category': 'Cameras',
    'condition': 'Like New',
    'originalPrice': 799.99,
    'discountedPrice': 599.99,
    'distance': 4.2,
    'seller': {
      'name': 'Drone Depot',
      'isVerified': true,
      'rating': 4.3,
      'image': 'https://randomuser.me/api/portraits/women/42.jpg',
    },
    'views': 287,
    'bids': 9,
    'images': [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Ym9zZSUyMGhlYWRwaG9uZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
    ],
    'description':
        'Bose QuietComfort 35 II noise-cancelling headphones. Some wear on the ear cushions but excellent sound quality and noise cancellation.',
    'specs': {
      'Type': 'Over-ear, wireless',
      'Battery Life': 'Up to 20 hours',
      'Connectivity': 'Bluetooth, 3.5mm',
      'Features': 'Active noise cancellation, built-in Google Assistant',
      'Included': 'Carrying case, charging cable, audio cable',
    },
    'auction': {
      'endDate': '2023-05-16',
      'startingPrice': 149.99,
      'currentBid': 179.99,
      'bidders': [
        {'name': 'Lauren B.', 'bid': 179.99, 'date': '2023-05-11'},
        {'name': 'Nathan C.', 'bid': 165.00, 'date': '2023-05-10'},
        {'name': 'Heather M.', 'bid': 165.00, 'date': '2023-05-11'},
        {'name': 'Nathan C.', 'bid': 165.00, 'date': '2023-05-10'},
        {'name': 'Heather M.', 'bid': 149.99, 'date': '2023-05-09'},
      ],
    },
  },

  {
    'id': 't3',
    'name': 'GoPro HERO9 Black',
    'category': 'Cameras',
    'condition': 'Like New',
    'originalPrice': 399.99,
    'discountedPrice': 279.99,
    'distance': 4.2,
    'seller': {
      'name': 'ActionCamRecyclers',
      'isVerified': true,
      'rating': 4.8,
      'image': 'https://randomuser.me/api/portraits/women/52.jpg',
    },
    'views': 203,
    'bids': 7,
    'images': [
      'https://images.unsplash.com/photo-1565130838609-c3a86655db61?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Z29wcm98ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
    ],
    'description':
        'GoPro HERO9 Black action camera in excellent condition. Includes original accessories and additional battery. Only used a few times.',
    'specs': {
      'Video': '5K30, 4K60, 1080p240',
      'Photo': '20MP',
      'Features': 'HyperSmooth 3.0, TimeWarp 3.0, Hindsight',
      'Waterproof': 'Up to 33ft (10m)',
      'Included': 'Protective case, 2 batteries, mounting accessories',
    },
    'auction': {
      'endDate': '2023-05-18',
      'startingPrice': 249.99,
      'currentBid': 279.99,
      'bidders': [
        {'name': 'Chris P.', 'bid': 279.99, 'date': '2023-05-13'},
        {'name': 'Melissa T.', 'bid': 265.00, 'date': '2023-05-12'},
        {'name': 'Jordan B.', 'bid': 249.99, 'date': '2023-05-11'},
      ],
    },
  },
];

// Premium products
final List<Map<String, dynamic>> premiumProducts = [
  {
    'id': 'pr1',
    'name': 'iMac 27" (2020)',
    'category': 'Computers',
    'condition': 'Good',
    'originalPrice': 1799.99,
    'discountedPrice': 1299.99,
    'distance': 5.3,
    'seller': {
      'name': 'ApplePro Recyclers',
      'isVerified': true,
      'rating': 4.9,
      'image': 'https://randomuser.me/api/portraits/men/12.jpg',
    },
    'views': 167,
    'bids': 4,
    'images': [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hY3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'description':
        '27-inch iMac (2020) with 5K Retina display, 3.3GHz 6-core Intel Core i5, 8GB RAM, 512GB SSD. Minor scratches on the base but screen is perfect.',
    'specs': {
      'Processor': '3.3GHz 6-core Intel Core i5',
      'RAM': '8GB DDR4',
      'Storage': '512GB SSD',
      'Display': '27-inch 5K Retina',
      'Graphics': 'AMD Radeon Pro 5300 4GB',
    },
    'auction': {
      'endDate': '2023-05-20',
      'startingPrice': 1199.99,
      'currentBid': 1299.99,
      'bidders': [
        {'name': 'Robert S.', 'bid': 1299.99, 'date': '2023-05-15'},
        {'name': 'Jennifer L.', 'bid': 1250.00, 'date': '2023-05-14'},
        {'name': 'William T.', 'bid': 1225.00, 'date': '2023-05-13'},
        {'name': 'Elizabeth K.', 'bid': 1199.99, 'date': '2023-05-12'},
      ],
    },
  },

  {
    'id': 'pr2',
    'name': 'Sony A7 III',
    'category': 'Cameras',
    'condition': 'Like New',
    'originalPrice': 1999.99,
    'discountedPrice': 1499.99,
    'distance': 6.7,
    'seller': {
      'name': 'ProCamera Recyclers',
      'isVerified': true,
      'rating': 4.8,
      'image': 'https://randomuser.me/api/portraits/women/82.jpg',
    },
    'views': 189,
    'bids': 5,
    'images': [
      'https://images.unsplash.com/photo-1516724562728-afc824a36e84?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c29ueSUyMGNhbWVyYXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    ],
    'description':
        'Sony A7 III mirrorless camera with 28-70mm lens. Excellent condition, low shutter count. Includes extra battery, charger, and camera bag.',
    'specs': {
      'Sensor': '24.2MP full-frame Exmor R CMOS',
      'ISO Range': '100-51,200 (expandable)',
      'Autofocus': '693-point phase-detection AF',
      'Video': '4K HDR',
      'Shutter Count': 'Approx. 5,200',
    },
    'auction': {
      'endDate': '2023-05-19',
      'startingPrice': 1399.99,
      'currentBid': 1499.99,
      'bidders': [
        {'name': 'Michael R.', 'bid': 1499.99, 'date': '2023-05-14'},
        {'name': 'Sarah J.', 'bid': 1450.00, 'date': '2023-05-13'},
        {'name': 'Daniel M.', 'bid': 1425.00, 'date': '2023-05-12'},
        {'name': 'Rebecca T.', 'bid': 1399.99, 'date': '2023-05-11'},
      ],
    },
  },
  // {
  //   'id': 'pr3',
  //   'name': 'LG 88" 8K OLED TV',
  //   'category': 'TVs',
  //   'condition': 'Like New',
  //   'originalPrice': 19999.99,
  //   'discountedPrice': 12999.99,
  //   'distance': 9.3,
  //   'image': 'https://images.unsplash.com/photo-1593784991095-a205069470b6',
  //   'seller': {
  //     'name': 'Luxury Electronics',
  //     'isVerified': true,
  //     'image': 'https://randomuser.me/api/portraits/men/92.jpg',
  //   },
  //   'views': 98,
  //   'bids': 2,
  // },
  // {
  //   'id': 'pr4',
  //   'name': 'Alienware Area-51 PC',
  //   'category': 'Computers',
  //   'condition': 'Good',
  //   'originalPrice': 4299.99,
  //   'discountedPrice': 2899.99,
  //   'distance': 6.7,
  //   'image': 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5',
  //   'seller': {
  //     'name': 'Gaming Hardware Recyclers',
  //     'isVerified': false,
  //     'image': 'https://randomuser.me/api/portraits/women/72.jpg',
  //   },
  //   'views': 132,
  //   'bids': 4,
  // },
];
